### PR TITLE
Add new LogMessageType "Fatal"

### PR DESCRIPTION
**Pull request by bufferUnderrun**
Hi,

This patch propose adding a new LogMessageType "Fatal".

According to this funny picture, but so true, this new higher level "Fatal" mean the application is gone to a better place :) aka has crashed.

niveau de log

Thanks

### CODE REVIEW

**Comment by geoperez** [comment]
Makes sense, NLog has Fatal too (https://github.com/NLog/NLog/wiki/Configuration-file#log-levels)

@mariodivece ?

**Comment by geoperez** [comment]
@bufferUnderrun Appveyor is failing, some compilation errors.

**Comment by bufferUnderrun** [comment]
it seems better.

Apologies for this dirty git history... I've some troubles accessing github and the only acces i have is editing file in the browser...

**Comment by geoperez** [comment]
Thank you!

**Pull request merged**
